### ISSUE TITLE
Add Left Joystick Movement for WMR

### ISSUE THREAD

**Issue by Neverdusk** [DrBibop/RoR2VRMod#38] opened 2021-05-28 16:39 UTC
I tried this mod and loved it, but the controls for WMR kept me from repeated runs - especially trackpad movement. 

On WMR controllers, it can be a bit unintuitive with the current setup. If you added movement and UI navigation to the left thumbstick (and assigned sprint to left thumbstick click), it would make the experience a lot easier.

**Comment by DrBibop** [comment] 2021-05-28 18:34
The reason I'm not using the joystick is because the joystick button opens the SteamVR overlay. You can change the movement axis in SteamVR by taking the axis value assigned to your trackpad and assign it to your joystick instead.

Marked as duplicate of: https://github.com/DrBibop/RoR2VRMod/issues/21

**Closed as completed by DrBibop** 2021-05-28 18:34 UTC
Labels: duplicate
